services:
  - type: web
    name: keycloak
    env: docker
    plan: standard
    autoDeploy: true
    envVars:
      - key: KC_DB
        value: postgres
      - key: KC_DB_URL
        fromDatabase:
          name: keycloak-db
          property: connectionString
      - key: KC_DB_USERNAME
        fromDatabase:
          name: keycloak-db
          property: user
      - key: KC_DB_PASSWORD
        fromDatabase:
          name: keycloak-db
          property: password
      - key: KC_HTTP_ENABLED
        value: "true"
      - key: KC_HOSTNAME_STRICT
        value: "false"
      - key: KC_PROXY
        value: "edge"
      - key: KC_BOOTSTRAP_ADMIN_USERNAME
        sync: false
      - key: KC_BOOTSTRAP_ADMIN_PASSWORD
        sync: false
    healthCheckPath: /
    ports:
      - 8080

databases:
  - name: keycloak-db
    plan: free
